language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: aY4SRK0vWHStNO3H0xmrulw6HCVeax+/mig+rqBjPYZ/PIr+ZOkoiQjOzMuCU+aR8n3jN2FCsEMfzo/hZhuL76JBM2m6xEZeapONIe3XtdF+xlt2+5QRk3mAKK6kqNoUUO8fORHhE7nZzRvrFPa0PzhNI9aL/8doVyMPFl0tIR7LELHZTmnd8L4wHkq8F8kuaBqAgIi3gwkzJcxj3MRf9OklYCk6AoVTdRRX961rV08yAaZCmGlOZpRFkDDpnuFS6sa46nuJDLd2QYHlfpxDOhgo5LFobwylsCJNIh5YfbSwr/hsKHJjVMa0XHb9/hphSAzEuWnF5NFzn4jR+QJ7qbn848kYkpywZROweri4jVJ7z1Bos37pLtNCdOFMar1Nrrq/1mKpBB/zEkZbwH37GCiKEuQHOgkVQ0xkLlIdxr2KyLRGWUpUbZKJET14DzgXZAvHdVZUgp6zWXCup9Gm/pVyZUETNYGKV0c4y41pk6E04zIoqIG4loFYbeaxOdV+z8FSPW0ADjKN2hIzZMiDCAGrngd2OFMunt7qe7lqhsgINCwzc76w6pEf8+b+cZFfE3dhyCLUEpcB9f2S0TfV7qdnLrAYbbE3P5ItGMAdRrPo4YJlmEHyLtR1SgATkZfEN+QmtoO2qGzNKb3ieGTplbxUCCA6I4nWekEXp0blmGU=
  app: floating-plateau-35610
  on:
    repo: bibiqiqi/weed_growing_app
